requires 'Cwd::utf8';
requires 'DB_File';
requires 'SQLite_File';
requires 'Digest::MD5';
requires 'Digest::SHA';
requires 'File::Basename';
requires 'File::Path';
requires 'HTTP::Tiny';
requires 'Hailo';
requires 'JSON';
requires 'JSON::XS';
requires 'JSON::PP';
requires 'IO::Socket::SSL';
requires 'POSIX';
requires 'Text::Fuzzy';
requires 'URI::URL';
requires 'local::lib';
requires 'Log::Any';
requires 'Log::Any::Adapter';
requires 'Log::Any::For::Std';
requires 'Math::Random::Secure';
requires 'HTML::TokeParser';

# Bundled Net::Jabber::Bot deps
# requires 'Net::Jabber::Bot';
requires 'Moose';
requires 'MooseX::Types';
requires 'Net::Jabber';
requires 'Time::HiRes';
requires 'Sys::Hostname';
requires 'Log::Log4perl';
requires 'Mozilla::CA';
